-- MySQL Script generated by MySQL Workbench
-- Sat Feb 23 17:48:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teamb-2019winter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teamb-2019winter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teamb-2019winter` DEFAULT CHARACTER SET utf8 ;
USE `teamb-2019winter` ;

-- -----------------------------------------------------
-- Table `teamb-2019winter`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamb-2019winter`.`users` (
  `e_mail` VARCHAR(64) NOT NULL,
  `fname` VARCHAR(128) NOT NULL,
  `lname` VARCHAR(128) NOT NULL,
  `hash_pwd` VARCHAR(255) NOT NULL,
  `sex` VARCHAR(4) NOT NULL,
  `user_seq_num` INT NOT NULL AUTO_INCREMENT,
  `admin` TINYINT NOT NULL,
  `hash` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`user_seq_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamb-2019winter`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamb-2019winter`.`sensor` (
  `mac_addr` CHAR(17) NOT NULL,
  `dev_id` INT NOT NULL AUTO_INCREMENT,
  `dev_name` VARCHAR(45) NOT NULL,
  `users_user_seq_num` INT NOT NULL,
  PRIMARY KEY (`dev_id`),
  INDEX `fk_sensor_users1_idx` (`users_user_seq_num` ASC) ,
  CONSTRAINT `fk_sensor_users1`
    FOREIGN KEY (`users_user_seq_num`)
    REFERENCES `teamb-2019winter`.`users` (`user_seq_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamb-2019winter`.`air_sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamb-2019winter`.`air_sensor` (
  `air_date` DATETIME NOT NULL,
  `lat` DOUBLE NOT NULL,
  `lon` DOUBLE NOT NULL,
  `RAW_PM` DOUBLE NOT NULL,
  `RAW_CO` DOUBLE NOT NULL,
  `RAW_SO2` DOUBLE NOT NULL,
  `RAW_NO2` DOUBLE NOT NULL,
  `RAW_O3` DOUBLE NOT NULL,
  `air_id` INT NOT NULL AUTO_INCREMENT,
  `AQI_PM` INT NOT NULL,
  `AQI_CO` INT NOT NULL,
  `AQI_NO2` INT NOT NULL,
  `AQI_SO2` INT NOT NULL,
  `AQI_O3` INT NOT NULL,
  `sensor_dev_id` INT NOT NULL,
  `temperature` DOUBLE NOT NULL,
  PRIMARY KEY (`air_id`),
  INDEX `fk_air_sensor_sensor1_idx` (`sensor_dev_id` ASC) ,
  CONSTRAINT `fk_air_sensor_sensor1`
    FOREIGN KEY (`sensor_dev_id`)
    REFERENCES `teamb-2019winter`.`sensor` (`dev_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamb-2019winter`.`heart_sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamb-2019winter`.`heart_sensor` (
  `heart_date` DATETIME NOT NULL,
  `heart_rate` INT NOT NULL,
  `heart_id` INT NOT NULL AUTO_INCREMENT,
  `heart_lat` DOUBLE NOT NULL,
  `heart_lon` DOUBLE NOT NULL,
  `users_user_seq_num` INT NOT NULL,
  PRIMARY KEY (`heart_id`),
  INDEX `fk_heart_sensor_users1_idx` (`users_user_seq_num` ASC) ,
  CONSTRAINT `fk_heart_sensor_users1`
    FOREIGN KEY (`users_user_seq_num`)
    REFERENCES `teamb-2019winter`.`users` (`user_seq_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
