<!doctype html>
<html class="fixed">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="Porto Admin - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="../assets/vendor/bootstrap/css/bootstrap.css" />
		<link rel="stylesheet" href="../assets/vendor/font-awesome/css/font-awesome.css" />
		<link rel="stylesheet" href="../assets/vendor/magnific-popup/magnific-popup.css" />
		<link rel="stylesheet" href="../assets/vendor/bootstrap-datepicker/css/datepicker3.css" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme.css" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/skins/default.css" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme-custom.css">

		<!-- Head Libs -->
		<script src="../assets/vendor/modernizr/modernizr.js"></script>
		
	</head>
	<body>
		<!-- start: page -->
		<section class="body-sign">
				<div class="center-sign">
					<form action ="../da" method = "post" name = "m">
					<div onclick ="document.forms['m'].submit();" style ="cursor : pointer;">
						<a class="logo pull-left">
							<img src="../assets/images/clogo.png" height="84" alt="Porto Admin" />
						</a>
					</div>
					</form>

				<div class="panel panel-sign">
					<div class="panel-title-sign mt-xl text-right">
						<h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i>Deregistration</h2>
					</div>
					<div class="panel-body">
						<div class="alert alert-info" style = "background-color: #f44242; color: #ffffff;">
							<p class="m-none text-semibold h6">This is ID Cancelation, If you want to delete all data from this app, Please click the button after fill out all text.</p>
						</div>

						<form action ="../da/deregistration2" method = "post" name = "idc">
						
						<fieldset class="mb-xl">
								
								<div class="form-group">
								
								<label class="col-md-3 control-label" for="nowpwd">Current Password</label>
								<div class="col-md-8">
									<input type="password" class="form-control" name="nowpwd" id="nowpwd">
								</div>
								</div>
												
								<div class="form-group">
								<label class="col-md-3 control-label" for="nowpwd_confirm">Password Comfirm</label>
								<div class="col-md-8">
									<input type="password" class="form-control" name="nowpwd_confirm" id="nowpwd_confirm">
								</div>
								</div>
						</fieldset>
						
						<div class="panel-footer">			
							<div class="row">
							<center>
								<button type="submit" style = "background-color:#f44242; border:0 solid #f44242" class="btn btn-primary">Delete Account</button>
						</form>
						
								<button type="button" style = "background-color:#002156; border:0 solid #002156" class="btn btn-primary"  onclick="history.back();"> Cancel</button>
							</center>
							</div>
						</div>	
					</div>
				</div>

				<p class="text-center text-muted mt-md mb-md">&copy; Copyright 2014. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
			</div>
		</section>
		<!-- end: page -->

		<!-- Vendor -->
		<script src="../assets/vendor/jquery/jquery.js"></script>
		<script src="../assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
		<script src="../assets/vendor/bootstrap/js/bootstrap.js"></script>
		<script src="../assets/vendor/nanoscroller/nanoscroller.js"></script>
		<script src="../assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="../assets/vendor/magnific-popup/magnific-popup.js"></script>
		<script src="../assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="../assets/javascripts/theme.js"></script>
		
		<!-- Theme Custom -->
		<script src="../assets/javascripts/theme.custom.js"></script>
		
		<!-- Theme Initialization Files -->
		<script src="../assets/javascripts/theme.init.js"></script>

	</body>
</html>