<!doctype html>
<html class="fixed">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="Porto Admin - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="../assets/vendor/bootstrap/css/bootstrap.css" />
		<link rel="stylesheet" href="../assets/vendor/font-awesome/css/font-awesome.css" />
		<link rel="stylesheet" href="../assets/vendor/magnific-popup/magnific-popup.css" />
		<link rel="stylesheet" href="../assets/vendor/bootstrap-datepicker/css/datepicker3.css" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme.css" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/skins/default.css" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme-custom.css">

		<!-- Head Libs -->
		<script src="../assets/vendor/modernizr/modernizr.js"></script>

		<!--script language = "javaScript">
			function check_onclick(){


			if(document.getElementById('email').value == ""  )
			{
				alert("Input your email");
			}
			else if(document.getElementById('firstName').value == ""  )
			{
				alert("Input your Firstname");
			}
			else if(document.getElementById('lastName').value == ""  )
			{
				alert("Input your Lastname");
			}
			else if(document.getElementById('pwd').value == ""  )
			{
				alert("Input your Password");
			}
			else if(document.getElementById('pwdConfirm').value == ""  )
			{
				alert("Input your Passwordconfirm");
			}


			/*
			theForm = document.signin;
			if(document.getElementById('username').value =="" || document.getElementById('pwd').value=="")
			{
				alert("Please Input User Information");
				if(document.getElementById('username').value =="")
				{
					alert("Please Input User E-mail");
				}
				*/
			}

		</script-->

	</head>
	<body>
		<!-- start: page -->
		<section class="body-sign">
			<div class="center-sign">
				<a href="/" class="logo pull-left">
					<img src="../assets/images/clogo.png" height="90" alt="Porto Admin" />
				</a>

				<div class="panel panel-sign">
					<div class="panel-title-sign mt-xl text-right">
						<h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i> ForgotchangePW</h2>
					</div>
					<form action="../da/signup3" method="post">
					<div class="panel-body text-center " >

							<h2 style="margin-bottom : 50px">E-mail check Success</h2>

							<div class="row">
								<div class="col-sm-8">

								</div>


							</div>
						</form>
						<form action="../da/signin" name="da03" method="post">
							<div onclick = "document.forms['da03'].submit();" style = "cursor : pointer;">
								<p class="text-center"><a><h4>Click here! Sign In!</h4></a></p>
							</div>
						</form>

					</div>
				</div>

				<p class="text-center text-muted mt-md mb-md">&copy; Copyright 2018. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
			</div>
		</section>
		<!-- end: page -->

		<!-- Vendor -->
		<script src="../assets/vendor/jquery/jquery.js"></script>
		<script src="../assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
		<script src="../assets/vendor/bootstrap/js/bootstrap.js"></script>
		<script src="../assets/vendor/nanoscroller/nanoscroller.js"></script>
		<script src="../assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="../assets/vendor/magnific-popup/magnific-popup.js"></script>
		<script src="../assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

		<!-- Theme Base, Components and Settings -->
		<script src="../assets/javascripts/theme.js"></script>

		<!-- Theme Custom -->
		<script src="../assets/javascripts/theme.custom.js"></script>

		<!-- Theme Initialization Files -->
		<script src="../assets/javascripts/theme.init.js"></script>

	</body>
</html>
