<!doctype html>
<html class="fixed">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<title>Daily Hreat Rate</title>
		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="JSOFT Admin - Responsive HTML5 Template">
		<meta name="author" content="JSOFT.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="../assets/vendor/bootstrap/css/bootstrap.css" />
		<link rel="stylesheet" href="../assets/vendor/font-awesome/css/font-awesome.css" />
		<link rel="stylesheet" href="../assets/vendor/magnific-popup/magnific-popup.css" />
		<link rel="stylesheet" href="../assets/vendor/bootstrap-datepicker/css/datepicker3.css" />

		<!-- Specific Page Vendor CSS -->
		<link rel="stylesheet" href="../assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" />
		<link rel="stylesheet" href="../assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
		<link rel="stylesheet" href="../assets/vendor/morris/morris.css" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme.css" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/skins/default.css" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme-custom.css">

		<!-- Head Libs -->
		<script src="../assets/vendor/modernizr/modernizr.js"></script>
		<head>
		<script type = "text/javascript">
		
			function getJSONMarkers() 
			{
				const markers = 
				[
					{
						name : "Q.I",
						location : [32.883837, -117.23274]
					},
					{
						name : "CMRR",
						location : [32.880797, -117.235567]
					},
					{	
						name : "fallen star",
						location : [32.881449, -117.235326]
					},
					{	
						name : "price center",
						location : [32.880329, -117.235835]
					}
				];
				return markers;
			}
			
			function loadmap() {
				const mapOptions = {
					center : new google.maps.LatLng(32.883837, -117.23274),
					zoom : 15,
					mapTypeId : google.maps.MapTypeId.ROADMAP
				}
				var map = new google.maps.Map(document.getElementById("map_hr"), mapOptions);
				
				const hrmapMarkers = getJSONMarkers();
				
				for (hrm of hrmapMarkers) {
					let marker = new google.maps.Marker({
						map : map,
						position : new google.maps.LatLng(hrm.location[0],hrm.location[1]),
						title :hrm.name
					})
				}
			}	
				window.onload=function() {
				loadmap();
				}  
			</script>

			<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBRHs1n9sW05pBxY2FFdRlAljm2orJbXXg&language=en&callback=initMap">
			</script>
			</head>
								
		<!--차트-->
				<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
		        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
				<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
				<script type="text/javascript">
				  google.charts.load('current', {'packages':['corechart']});
				  google.charts.setOnLoadCallback(drawChart);

				  function drawChart() {
						var jsonData = $.ajax({
								url: "http://teamb-iot.calit2.net/da/hrjson",
								dataType:"json",
								async: false
								}).responseText;
				// Create our data table out of JSON data loaded from server.
				var data = new google.visualization.DataTable(jsonData);



				var options = {
						width: 800, height: 480,
				};
				var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));
				chart.draw(data, options);
				setTimeout(drawChart, 3000);
				  }
				</script>

				<script type="text/javascript">
				function autoRefresh_div()
				{
				var currentLocation = window.location;
				$("#rehr").load(currentLocation + ' #rehr');
				}
				setInterval('autoRefresh_div()', 1000);
				</script>

	</head>
	<body>
		<section class="body">

			<!-- start: header -->
			<header class="header">
				<div class="logo-container">
					<form action ="../da" method = "post" name = "j">
					<div onclick ="document.forms['j'].submit();" style ="cursor : pointer;">
					<a class="logo">
						<img src="../assets/images/longlogo.png" height="70" alt="JSOFT Admin" />
					</a>
					</div>
					</form>
					<div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
						<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
					</div>
				</div>

				<!-- start: search & user box -->
				<div class="header-right">

					<span class="separator"></span>

					<div id="userbox" class="userbox">
						<a href="#" data-toggle="dropdown">
							<figure class="profile-picture">
								<img src="../assets/images/!logged-user.jpg" alt="Joey" class="img-circle" data-lock-picture="../assets/images/!logged-user.jpg" />
							</figure>
							<div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@JSOFT.com">
								<span class="name"><?php if(isset($_SESSION['userName']))
														{
															echo $_SESSION["userName"];
														}
														else {
															echo "<script>alert('wrong connetion!'); history.back();</script>";
														}

														?></span>
							</div>
						</a>
					</div>
				</div>
				<!-- end: search & user box -->
			</header>
			<!-- end: header -->

			<div class="inner-wrapper">
				<!-- start: sidebar -->
				<aside id="sidebar-left" class="sidebar-left">

					<div class="sidebar-header">
						<div class="sidebar-title">
						MENU
						</div>
						<div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
							<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
						</div>
					</div>

					<div class="nano">
						<div class="nano-content">
							<nav id="menu" class="nav-main" role="navigation">
								<ul class="nav nav-main">
									<li class="nav-active">
									<form action ="../da" method = "post" name = "r">
									<div onclick ="document.forms['r'].submit();" style ="cursor : pointer;">
											<Br>&nbsp;&nbsp;&nbsp;<i class="fa fa-home" aria-hidden="true"></i>
											<span>Home</span>
									</div>
									</form>
									</li>

									<li class="nav-active">
										<a href="../da/temp">
											<span>Temperature</span>
										</a>
									</li>

									<li class="nav-active">
										<a href="../da/hr">
											<span>Heart Rate</span>
										</a>
									</li>

									<li class="nav-active">
										<a href="../da/air">
											<span>Air Quality</span>
										</a>
									</li>

									<li class="nav-active">
									<form action ="../da/profile" method = "post" name = "prof">
									<div onclick ="document.forms['prof'].submit();" style ="cursor : pointer;">
											<span class="pull-right label label-primary"></span>
											<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User Profile</span>
									</form>
									</li>

									<li class="nav-active">
									<form action ="../da/signout" method = "post" name = "r">
									<div onclick ="document.forms['r'].submit();" style ="cursor : pointer;">
											<span class="pull-right label label-primary"></span>
											<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sign Out</span>
									</div>
									</form>
									</li>
								</ul>
						</div>
					</div>
				</aside>
				<!-- end: sidebar -->


			<!-- 위에 -->
				<section role="main" class="content-body">
					<header class="page-header">
						<h2>Heart Rate</h2>>
					</header>


				<!-- 콘텐츠 -->

						<div class="row">
						<div class="col-md-12" >
							<img src = "../assets/images/realtimehr.png" width="400">
							<br><br>
							
							<div id = "rehr">
								<section class="panel panel-featured-left panel-featured-secondary">
									<div class="panel-body">
									<div style="text-align: center;">
										<img src = "../assets/images/hr.png" width = "200" >
										<h2 class="title">HR</h2>
										<font color=red><h1><strong><?php echo $heart_rate?></strong></h1></font>	
									</div>
									</div>
								</section>	
							</div>
						</div>
						</div>

						<hr>
						<img src = "../assets/images/historyhr.png" width="400">
						<form id="frm" action="action.jsp">
							<div>
							<p style="text-align: center;">
								Date:
								<input type="date" id="userdate" name="userdate"
											value="2019-02-07">
								<input type="submit" value="SERCH">
							</p>
							</div>
						</form>

						<!--구글맵이다-->
								<center>
								<div id="map_hr" style="width:550px; height:300px;" align = "center"></div>
								<br>
								</center>

						<div class="row">
						<div class="col-md-5">
						<table style =text-align:center; border= 1 width ="500" height ="350" >
							<tr>
								<td> <strong>HR </strong> </td>
								<td> <strong>Date </strong> </td>
							</tr>
							<?php
									
							 foreach ($row3 as $row4) {
								 echo "<tr>";
										echo    "<td>"; echo $row4['heart_rate'];
										echo    "</td>";

										 echo    "<td>"; echo $row4['heart_date'];
										 echo    "</td>";
								 echo    "</tr>";
							} ?>
						</table>
						</div>


						<div class="row">
						<div class="col-md-4">
								<!--<div class="panel-body">
								<tr chart>-->
								 <div id="curve_chart" style="width: 500px; height: 400px"></div>
						</div>
						</div>



		<!-- Vendor -->
		<script src="../assets/vendor/jquery/jquery.js"></script>
		<script src="../assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
		<script src="../assets/vendor/bootstrap/js/bootstrap.js"></script>
		<script src="../assets/vendor/nanoscroller/nanoscroller.js"></script>
		<script src="../assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="../assets/vendor/magnific-popup/magnific-popup.js"></script>
		<script src="../assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

		<!-- Specific Page Vendor -->
		<script src="../assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
		<script src="../assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
		<script src="../assets/vendor/jquery-appear/jquery.appear.js"></script>
		<script src="../assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
		<script src="../assets/vendor/jquery-easypiechart/jquery.easypiechart.js"></script>
		<script src="../assets/vendor/flot/jquery.flot.js"></script>
		<script src="../assets/vendor/flot-tooltip/jquery.flot.tooltip.js"></script>
		<script src="../assets/vendor/flot/jquery.flot.pie.js"></script>
		<script src="../assets/vendor/flot/jquery.flot.categories.js"></script>
		<script src="../assets/vendor/flot/jquery.flot.resize.js"></script>
		<script src="../assets/vendor/jquery-sparkline/jquery.sparkline.js"></script>
		<script src="../assets/vendor/raphael/raphael.js"></script>
		<script src="../assets/vendor/morris/morris.js"></script>
		<script src="../assets/vendor/gauge/gauge.js"></script>
		<script src="../assets/vendor/snap-svg/snap.svg.js"></script>
		<script src="../assets/vendor/liquid-meter/liquid.meter.js"></script>
		<script src="../assets/vendor/jqvmap/jquery.vmap.js"></script>
		<script src="../assets/vendor/jqvmap/data/jquery.vmap.sampledata.js"></script>
		<script src="../assets/vendor/jqvmap/maps/jquery.vmap.world.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.africa.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.asia.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.australia.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.europe.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.north-america.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.south-america.js"></script>

		<!-- Theme Base, Components and Settings -->
		<script src="../assets/javascripts/theme.js"></script>

		<!-- Theme Custom -->
		<script src="../assets/javascripts/theme.custom.js"></script>

		<!-- Theme Initialization Files -->
		<script src="../assets/javascripts/theme.init.js"></script>


		<!-- Examples -->
		<script src="../assets/javascripts/dashboard/examples.dashboard.js"></script>
	</body>
</html>
