<html>
    <head>
        <meta charset="utf-8"/>
        <title>Daily Assi.</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='{{ base_url() }}/css/style.css' rel='stylesheet' type='text/css'>
    </head>
    <body>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>

			<form action="../da/signin" name="da02" method="post">
				<div onclick = "document.forms ['da02'].submit();" style = "cursor : pointer;">
					<p style="text-align: center;">
					<a> <img src="../assets/images/mainlogo.png" width="400"  height="400"> </a>
					</p>
				</div>
			</form>
    </body>
</html>
