<!doctype html>
<html class="fixed">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<title>Daily Assi.</title>
		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="JSOFT Admin - Responsive HTML5 Template">
		<meta name="author" content="JSOFT.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="../assets/vendor/bootstrap/css/bootstrap.css" />
		<link rel="stylesheet" href="../assets/vendor/font-awesome/css/font-awesome.css" />
		<link rel="stylesheet" href="../assets/vendor/magnific-popup/magnific-popup.css" />
		<link rel="stylesheet" href="../assets/vendor/bootstrap-datepicker/css/datepicker3.css" />

		<!-- Specific Page Vendor CSS -->
		<link rel="stylesheet" href="../assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" />
		<link rel="stylesheet" href="../assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
		<link rel="stylesheet" href="../assets/vendor/morris/morris.css" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme.css" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/skins/default.css" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme-custom.css">

		<!-- Head Libs -->
		<script src="../assets/vendor/modernizr/modernizr.js"></script>

		<script type="text/javascript">
				function autoRefresh_div()
				{
				var currentLocation = window.location;
				$("#redata").load(currentLocation + ' #redata');
				}

				setInterval('autoRefresh_div()', 100);   
		</script>

</head>
	<body>
		<section class="body">

			<!-- start: header -->
			<header class="header">
				<div class="logo-container">
					<form action ="../da" method = "post" name = "j">
					<div onclick ="document.forms['j'].submit();" style ="cursor : pointer;">
					<a class="logo">
						<img src="../assets/images/longlogo.png" height="70" alt="JSOFT Admin" />
					</a>
					</div>
					</form>
					<div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
						<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
					</div>
				</div>

				<!-- start: search & user box -->
				<div class="header-right">

					<span class="separator"></span>

					<div id="userbox" class="userbox">
						<a href="#" data-toggle="dropdown">
							<figure class="profile-picture">
								<img src="../assets/images/!logged-user.jpg" alt="Joey" class="img-circle" data-lock-picture="../assets/images/!logged-user.jpg" />
							</figure>
							<div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@JSOFT.com">
								<span class="name"><?php if(isset($_SESSION['userName']))
														{
															echo $_SESSION["userName"];
														}
														else {
															echo "<script>alert('Wrong Connection!'); history.back();</script>";
														}

														?> </span>
							</div>
						</a>
					</div>
				</div>
				<!-- end: search & user box -->
			</header>
			<!-- end: header -->

			<div class="inner-wrapper">
				<!-- start: sidebar -->
				<aside id="sidebar-left" class="sidebar-left">

					<div class="sidebar-header">
						<div class="sidebar-title">
						MENU
						</div>
						<div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
							<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
						</div>
					</div>

					<div class="nano">
						<div class="nano-content">
							<nav id="menu" class="nav-main" role="navigation">
								<ul class="nav nav-main">
									<li class="nav-active">
									<form action ="../da" method = "post" name = "r">
									<div onclick ="document.forms['r'].submit();" style ="cursor : pointer;">
											<Br>&nbsp;&nbsp;&nbsp;<i class="fa fa-home" aria-hidden="true"></i>
											<span>Home</span>
									</div>
									</form>
									</li>

									<li class="nav-active">
										<a href="../da/temp">
											<span>Temperature</span>
										</a>
									</li>

									<li class="nav-active">
										<a href="../da/hr">
											<span>Heart Rate</span>
										</a>
									</li>

									<li class="nav-active">
										<a href="../da/air">
											<span>Air Quality</span>
										</a>
									</li>

									<li class="nav-active">
									<form action ="../da/profile" method = "post" name = "prof">
									<div onclick ="document.forms['prof'].submit();" style ="cursor : pointer;">
											<span class="pull-right label label-primary"></span>
											<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User Profile</span>
									</form>
									</li>

									<li class="nav-active">
									<form action ="../da/signout" method = "post" name = "o">
									<div onclick ="document.forms['o'].submit();" style ="cursor : pointer;">
											<span class="pull-right label label-primary"></span>
											<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sign Out</span>
									</div>
									</form>
									</li>

								</ul>
						</div>
					</div>
				</aside>

				<!-- end: sidebar -->
				<div id = "redata">
				<section role="main" class="content-body">
					<header class="page-header">
						<h2>Home</h2>

						<div class="right-wrapper pull-right">

							<a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
						</div>
					</header>

						<div class="row">
						<div class="col-md-6">
							<section class="panel">
								<header class="panel-heading">
									<div class="panel-actions">
										<a href="#" class="fa fa-caret-down"></a>
										<a href="#" class="fa fa-times"></a>
									</div>
									<h2 class="panel-title">Today's cloth</h2>
									<p class="panel-subtitle">Recommend appropriate clothes, based on real-time temperatures! </p>
								</header>
								<div class="panel-body">
								<p style="text-align: center;">
								<a href = "../da/temp"> <img src = "../assets/images/sun.png">
								<img src = "../assets/images/clothing.png"></a><BR>
								<h1 align = center> <?php echo $temperature[0]?>°F &nbsp; &nbsp; &nbsp; Thin Cloth </h1>
								</p>
								</div>
							</section>
						</div>


						<div class="row">
						<div class="col-md-6">
							<section class="panel">
								<header class="panel-heading">
									<div class="panel-actions">
										<a href="#" class="fa fa-caret-down"></a>
										<a href="#" class="fa fa-times"></a>
									</div>
									<h2 class="panel-title">Heart Rate</h2>
									<p class="panel-subtitle">Check your Heart Rate and Respiratory Rate</p>
								</header>

							<div class="panel-body">
							<BR> <BR>

								<div class="col-md-12">
								   <section class="panel panel-featured-left panel-featured-secondary">
									  <div class="panel-body">
										 <div class="widget-summary">
											<p style="text-align: center;">
											<div class="widget-summary-col">
											   <div class="summary">
											   <div  style = " float : left">
												<img src = "../assets/images/hr.png" width = "100" >
												</div>
												  <div class="info" style =" float : left">
													<h4 class="title">HR</h4>
														<strong class="amount">
														<?php if(isset($heart_rate))
																echo $heart_rate;
															else echo "non";
														?>
														</h1></strong>
												  </div>
											   </div>
											   <div class="summary-footer">
												  <a class="text-muted text-uppercase" href = "http://192.168.33.99/da/hr">(withdraw)</a>
											   </div>
											 </P>
											</div>
										 </div>
								   </div>
								   </section>
							   </div>
							<BR> <BR>
							</div>
						</div>
						</div>


					</div>


						<!--공기쓰-->
						<div class="column">
							<div class="col-md-6">
							<section class="panel panel-transparent">
								<header class="panel-heading">
									<div class="panel-actions">
										<a href="#" class="fa fa-caret-down"></a>
										<a href="#" class="fa fa-times"></a>
									</div>
									<h2 class="panel-title">Air Stats</h2>
								</header>
								<section class="panel panel-featured-left panel-featured-quartenary">
										 <div class="panel-body">
											 <div class="widget-summary">
												<p style="text-align: center;">
												<div class="widget-summary-col">
												   <div class="summary">
												   <div  style = " float : left">
													<img src = "../assets/images/PM.png" width = "100" >
													</div>
													  <div class="info" style =" float : left">
														<h4 class="title"></h4><strong class="amount"><?php echo $row2['AQI_PM']?></strong>

													  </div>
												   </div>
												   <div class="summary-footer">
												   </div>
												 </P>
												</div>
											 </div>
										</div>
								</section>

								<section class="panel panel-featured-left panel-featured-quartenary">
										  <div class="panel-body">
											 <div class="widget-summary">
												<p style="text-align: center;">
												<div class="widget-summary-col">
												   <div class="summary">
												   <div  style = " float : left">
													<img src = "../assets/images/CO.png" width = "100" >
													</div>
													  <div class="info" style =" float : left">
														<h4 class="title"></h4><strong class="amount"><?php echo $row2['AQI_CO']?></strong>

													  </div>
												   </div>
												   <div class="summary-footer">
												   </div>
												 </P>
												</div>
											 </div>
									   </div>
								</section>

								<section class="panel panel-featured-left panel-featured-quartenary">
										  <div class="panel-body">
											 <div class="widget-summary">
												<p style="text-align: center;">
												<div class="widget-summary-col">
												   <div class="summary">
												   <div  style = " float : left">
													<img src = "../assets/images/SO2.png" width = "100" >
													</div>
													  <div class="info" style =" float : left">
														<h4 class="title"></h4><strong class="amount"><?php echo $row2['AQI_SO2']?></strong>

													  </div>
												   </div>
												   <div class="summary-footer">
												   </div>
												 </P>
												</div>
											 </div>
									   </div>
								</section>
						</div>
						</div>


						<br> <br> <br>
						<div class="row">
						<div class="col-md-6">

							<section class="panel panel-featured-left panel-featured-quartenary">
									  <div class="panel-body">
										 <div class="widget-summary">
											<p style="text-align: center;">
											<div class="widget-summary-col">
											   <div class="summary">
											   <div  style = " float : left">
												<img src = "../assets/images/NO2.png" width = "100" >
												</div>
												  <div class="info" style =" float : left">
													<h4 class="title"></h4><strong class="amount"><?php echo $row2['AQI_NO2']?></strong>
												  </div>
											   </div>
											   <div class="summary-footer">
											   </div>
											 </P>
											</div>
										 </div>
								   </div>
							</section>

							<section class="panel panel-featured-left panel-featured-quartenary">
									  <div class="panel-body">
										 <div class="widget-summary">
											<p style="text-align: center;">
											<div class="widget-summary-col">
											   <div class="summary">
											   <div  style = " float : left">
												<img src = "../assets/images/O3.png" width = "100" >
												</div>
												  <div class="info" style =" float : left">
													<h4 class="title"></h4><strong class="amount"><?php echo $row2['AQI_O3']?></strong>
												  </div>
											   </div>
											   <div class="summary-footer">
											   </div>
											 </P>
											</div>
										 </div>
								   </div>
							</section>
						</div>
						</div>
				</section>
				</div>

		<!-- Vendor -->
		<script src="../assets/vendor/jquery/jquery.js"></script>
		<script src="../assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
		<script src="../assets/vendor/bootstrap/js/bootstrap.js"></script>
		<script src="../assets/vendor/nanoscroller/nanoscroller.js"></script>
		<script src="../assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="../assets/vendor/magnific-popup/magnific-popup.js"></script>
		<script src="../assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

		<!-- Specific Page Vendor -->
		<script src="../assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
		<script src="../assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
		<script src="../assets/vendor/jquery-appear/jquery.appear.js"></script>
		<script src="../assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
		<script src="../assets/vendor/jquery-easypiechart/jquery.easypiechart.js"></script>
		<script src="../assets/vendor/flot/jquery.flot.js"></script>
		<script src="../assets/vendor/flot-tooltip/jquery.flot.tooltip.js"></script>
		<script src="../assets/vendor/flot/jquery.flot.pie.js"></script>
		<script src="../assets/vendor/flot/jquery.flot.categories.js"></script>
		<script src="../assets/vendor/flot/jquery.flot.resize.js"></script>
		<script src="../assets/vendor/jquery-sparkline/jquery.sparkline.js"></script>
		<script src="../assets/vendor/raphael/raphael.js"></script>
		<script src="../assets/vendor/morris/morris.js"></script>
		<script src="../assets/vendor/gauge/gauge.js"></script>
		<script src="../assets/vendor/snap-svg/snap.svg.js"></script>
		<script src="../assets/vendor/liquid-meter/liquid.meter.js"></script>
		<script src="../assets/vendor/jqvmap/jquery.vmap.js"></script>
		<script src="../assets/vendor/jqvmap/data/jquery.vmap.sampledata.js"></script>
		<script src="../assets/vendor/jqvmap/maps/jquery.vmap.world.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.africa.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.asia.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.australia.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.europe.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.north-america.js"></script>
		<script src="../assets/vendor/jqvmap/maps/continents/jquery.vmap.south-america.js"></script>

		<!-- Theme Base, Components and Settings -->
		<script src="../assets/javascripts/theme.js"></script>

		<!-- Theme Custom -->
		<script src="../assets/javascripts/theme.custom.js"></script>

		<!-- Theme Initialization Files -->
		<script src="../assets/javascripts/theme.init.js"></script>


		<!-- Examples -->
		<script src="../assets/javascripts/dashboard/examples.dashboard.js"></script>
	</body>
</html>
