<!doctype html>
<html class="fixed">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="Porto Admin - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="../assets/vendor/bootstrap/css/bootstrap.css" />
		<link rel="stylesheet" href="../assets/vendor/font-awesome/css/font-awesome.css" />
		<link rel="stylesheet" href="../assets/vendor/magnific-popup/magnific-popup.css" />
		<link rel="stylesheet" href="../assets/vendor/bootstrap-datepicker/css/datepicker3.css" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme.css" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/skins/default.css" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="../assets/stylesheets/theme-custom.css">

		<!-- Head Libs -->
		<script src="../assets/vendor/modernizr/modernizr.js"></script>

		<!--script language = "javaScript">
			function check_onclick(){
				
				
			if(document.getElementById('email').value == ""  )
			{
				alert("Input your email");
			}
			else if(document.getElementById('firstName').value == ""  )
			{
				alert("Input your Firstname");
			}
			else if(document.getElementById('lastName').value == ""  )
			{
				alert("Input your Lastname");
			}
			else if(document.getElementById('pwd').value == ""  )
			{
				alert("Input your Password");
			}
			else if(document.getElementById('pwdConfirm').value == ""  )
			{
				alert("Input your Passwordconfirm");
			}
			
			
			/*	
			theForm = document.signin;
			if(document.getElementById('username').value =="" || document.getElementById('pwd').value=="")
			{
				alert("Please Input User Information");
				if(document.getElementById('username').value =="")
				{
					alert("Please Input User E-mail");
				}
				*/
			}
			
		</script-->
		
	</head>
	<body>
		<!-- start: page -->
		<section class="body-sign">
			<div class="center-sign">
				<a href="/" class="logo pull-left">
					<img src="../assets/images/clogo.png" height="90" alt="Porto Admin" />
				</a>
				
				<div class="panel panel-sign">
					<div class="panel-title-sign mt-xl text-right">
						<h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i> Sign Up</h2>
					</div>
					<form action="../da/signup3" method="post">
					<div class="panel-body">
						
							<label>E-mail Address</label>
							<div class="form-group mb-none">
							
							<div class="row">
								<div class="col-sm-10 mb-lg" style = "float : left";>
									<input id="email" name="email" type="email" class="form-control input-lg" value="<?php if(isset($_POST['email'])) echo $_POST['email']; ?>"/>
									
								</div>
		
								
							</div>
							
						

						
							
							
							
							<!--	<div class="form-group mb-none">
								<div class="col-sm-6 mb-lg">
											<label>First Name</label>
											<input name="name" type="name" class="form-control input-lg" />
										</div>
									
								<div class="col-sm-6 mb-lg">
											<label>Last Name</label>
											<input name="name" type="name" class="form-control input-lg" />
										</div>
								</div>!-->
							
							<div class="form-group mb-none">
								<div class="row">
									<div class="col-sm-6 mb-lg">
										<label>First Name</label>
										<input id="firstName" name="fname" type="name" class="form-control input-lg" />
									</div>
									<div class="col-sm-6 mb-lg">
										<label>Last Name</label>
										<input id="lastName" name="lname" type="name" class="form-control input-lg" />
									</div>
								</div>

							<div class="form-group mb-none">
								<div class="row">
									<div class="col-sm-6 mb-lg">
										<label>Password</label>
										<input id="pwd" name="pwd" type="password" class="form-control input-lg" />
									</div>
									<div class="col-sm-6 mb-lg">
										<label>Password Confirmation</label>
										<input id="pwdConfirm" name="pwd_confirm" type="password" class="form-control input-lg" />
									</div>
									
								<div class="form-group mb-lg">
									<label>&nbsp;&nbsp;&nbsp; Gender</label> &nbsp;&nbsp;&nbsp;
									<input type="radio" name="Gender" value="m" checked="checked" />male &nbsp;&nbsp;
									<input type="radio" name="Gender" value="f" />female
								</div>
										
								<span class="mt-lg mb-lg line-thru text-center text-uppercase">
									<span>or</span>
								</span>
								
							</div>

							
							

							<div class="row">
								<div class="col-sm-8">
								   
								</div>
								
								<div class="col-sm-4 text-right">
								   <button type="submit" class="btn btn-primary hidden-xs">Sign Up</button>
								
								</div>
							</div>						 
						</form>
						<form action="../da/signin" name="da03" method="post">
							<div onclick = "document.forms['da03'].submit();" style = "cursor : pointer;">
								<p class="text-center">Already have an account? <a>Sign In!</a></p>
							</div>
						</form>
						
					</div>
				</div>

				<p class="text-center text-muted mt-md mb-md">&copy; Copyright 2018. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
			</div>
		</section>
		<!-- end: page -->

		<!-- Vendor -->
		<script src="../assets/vendor/jquery/jquery.js"></script>
		<script src="../assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
		<script src="../assets/vendor/bootstrap/js/bootstrap.js"></script>
		<script src="../assets/vendor/nanoscroller/nanoscroller.js"></script>
		<script src="../assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="../assets/vendor/magnific-popup/magnific-popup.js"></script>
		<script src="../assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="../assets/javascripts/theme.js"></script>
		
		<!-- Theme Custom -->
		<script src="../assets/javascripts/theme.custom.js"></script>
		
		<!-- Theme Initialization Files -->
		<script src="../assets/javascripts/theme.init.js"></script>

	</body>
</html>